In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('C://Users/Gray/Desktop/git_repos/IPL-2020/Dummy Data/matches_complete.csv')

In [35]:
li = (df['team1'].unique()).astype(str)
arr = ['2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020']
dict = {}
for i in range(len(li)):
    print(li[i].upper())
    dict[li[i].upper()] = i

KOLKATA KNIGHT RIDERS
CHENNAI SUPER KINGS
RAJASTHAN ROYALS
MUMBAI INDIANS
DECCAN CHARGERS
KINGS XI PUNJAB
ROYAL CHALLENGERS BANGALORE
DELHI DAREDEVILS
KOCHI TUSKERS KERALA
PUNE WARRIORS
SUNRISERS HYDERABAD
RISING PUNE SUPERGIANTS
GUJARAT LIONS
RISING PUNE SUPERGIANT
DELHI CAPITALS


In [4]:
percentage = (pd.DataFrame(index=[li], columns=[arr])).fillna(0)
x = np.array(percentage).astype(float)

In [6]:
def func_tab(season, toss_count, match_count):
    j = int(season)-2008
    for i in range(len(li)):
        if(match_count[i]!=0):
            #print(match_count)
            x[i][j] = toss_count[i]/match_count[i]
            if(j+2008 == 2019):
                print(toss_count)
                print(match_count)
            #print(x[i][j])
        

In [7]:
data = np.array(df)
toss_count = np.zeros((15,1))
match_count = np.zeros((15, 1))
prev_season = 2008
for i in range(756):
    toss_winner = df['toss_winner'][i]
    match_winner = df['winner'][i]
    season = (df['season'][i]) 
    pos = dict[toss_winner]
    if(season!=prev_season):
        func_tab(season, toss_count, match_count)
        prev_season = season
    match_count[pos] += 1
    if(match_winner==toss_winner):
        toss_count[pos] += 1
func_tab(2020, toss_count, match_count)

[[49.]
 [50.]
 [37.]
 [50.]
 [19.]
 [32.]
 [39.]
 [35.]
 [ 4.]
 [ 3.]
 [21.]
 [ 3.]
 [10.]
 [ 5.]
 [ 0.]]
[[87.]
 [77.]
 [69.]
 [90.]
 [43.]
 [75.]
 [77.]
 [80.]
 [ 8.]
 [20.]
 [42.]
 [ 7.]
 [15.]
 [ 6.]
 [ 0.]]
[[49.]
 [50.]
 [37.]
 [50.]
 [19.]
 [32.]
 [39.]
 [35.]
 [ 4.]
 [ 3.]
 [21.]
 [ 3.]
 [10.]
 [ 5.]
 [ 0.]]
[[87.]
 [77.]
 [69.]
 [90.]
 [43.]
 [75.]
 [77.]
 [80.]
 [ 8.]
 [20.]
 [42.]
 [ 7.]
 [15.]
 [ 6.]
 [ 0.]]
[[49.]
 [50.]
 [37.]
 [50.]
 [19.]
 [32.]
 [39.]
 [35.]
 [ 4.]
 [ 3.]
 [21.]
 [ 3.]
 [10.]
 [ 5.]
 [ 0.]]
[[87.]
 [77.]
 [69.]
 [90.]
 [43.]
 [75.]
 [77.]
 [80.]
 [ 8.]
 [20.]
 [42.]
 [ 7.]
 [15.]
 [ 6.]
 [ 0.]]
[[49.]
 [50.]
 [37.]
 [50.]
 [19.]
 [32.]
 [39.]
 [35.]
 [ 4.]
 [ 3.]
 [21.]
 [ 3.]
 [10.]
 [ 5.]
 [ 0.]]
[[87.]
 [77.]
 [69.]
 [90.]
 [43.]
 [75.]
 [77.]
 [80.]
 [ 8.]
 [20.]
 [42.]
 [ 7.]
 [15.]
 [ 6.]
 [ 0.]]
[[49.]
 [50.]
 [37.]
 [50.]
 [19.]
 [32.]
 [39.]
 [35.]
 [ 4.]
 [ 3.]
 [21.]
 [ 3.]
 [10.]
 [ 5.]
 [ 0.]]
[[87.]
 [77.]
 [69.]
 [90.]
 [43.]
 [75.]
 [77

In [9]:
x

array([[0.        , 0.5       , 0.38461538, 0.45      , 0.51851852,
        0.55882353, 0.5       , 0.52727273, 0.53968254, 0.55072464,
        0.56410256, 0.56321839, 0.57608696],
       [0.        , 0.6       , 0.58333333, 0.59090909, 0.64516129,
        0.63157895, 0.67391304, 0.66071429, 0.63636364, 0.63636364,
        0.63636364, 0.64935065, 0.64044944],
       [0.        , 0.81818182, 0.73333333, 0.66666667, 0.64285714,
        0.55263158, 0.55102041, 0.54385965, 0.53968254, 0.53968254,
        0.53968254, 0.53623188, 0.525     ],
       [0.        , 0.5       , 0.5       , 0.56521739, 0.55172414,
        0.55      , 0.57692308, 0.56896552, 0.55384615, 0.55405405,
        0.56470588, 0.55555556, 0.57142857],
       [0.        , 0.22222222, 0.47368421, 0.5       , 0.5       ,
        0.44186047, 0.44186047, 0.44186047, 0.44186047, 0.44186047,
        0.44186047, 0.44186047, 0.44186047],
       [0.        , 0.5       , 0.57142857, 0.42105263, 0.4137931 ,
        0.43243243, 0.45454

In [10]:
percentage = (pd.DataFrame(x, index=[li], columns=[arr])).fillna(0)

In [11]:
df['Match Won after winning Toss Team A'] = 't'
df['Match Won after winning Toss Team B'] = 't'

In [12]:
for i in range(756):
    season = df['season'][i]
    teamA = df['team1'][i]
    teamB = df['team2'][i]
    diff = int(season)-2008
    posA = dict[teamA]
    posB = dict[teamB]
    df['Match Won after winning Toss Team A'][i] = x[posA][diff]
    df['Match Won after winning Toss Team B'][i] = x[posB][diff]

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':


In [63]:
percentage.to_csv("MatchWonAfterWinningToss.csv")

In [69]:
df.head()

Unnamed: 0  id  season        city        date                  team1  \
0           0  60    2008   Bangalore  2008-04-18  Kolkata Knight Riders   
1           1  61    2008  Chandigarh  2008-04-19    Chennai Super Kings   
2           2  62    2008       Delhi  2008-04-19       Rajasthan Royals   
3           3  63    2008      Mumbai  2008-04-20         Mumbai Indians   
4           4  64    2008     Kolkata  2008-04-20        Deccan Chargers   

                         team2                  toss_winner toss_decision  \
0  Royal Challengers Bangalore  Royal Challengers Bangalore         field   
1              Kings XI Punjab          Chennai Super Kings           bat   
2             Delhi Daredevils             Rajasthan Royals           bat   
3  Royal Challengers Bangalore               Mumbai Indians           bat   
4        Kolkata Knight Riders              Deccan Chargers           bat   

   result  ...                                       venue    umpire1  \
0  normal  ...                       M Chinnaswamy Stadium  Asad Rauf   
1  normal  ...  Punjab Cricket Association Stadium, Mohali  MR Benson   
2  normal  ...                            Feroz Shah Kotla  Aleem Dar   
3  normal  ...                            Wankhede Stadium   SJ Davis   
4  normal  ...                                Eden Gardens  BF Bowden   

          umpire2  umpire3 Top Batsmen Points(Team A)  \
0     RE Koertzen      NaN                        536   
1      SL Shastri      NaN                        807   
2  GA Pratapkumar      NaN                        642   
3       DJ Harper      NaN                        556   
4     K Hariharan      NaN                        617   

  Top Batsmen Points(Team B) Top Baller Points(Team A)  \
0                        509                       730   
1                        804                       564   
2                        536                       571   
3                        509                       970   
4                        536                       603   

  Top Baller Points(Team B) Match Won after winning Toss Team A  \
0                       393                                   0   
1                       538                                   0   
2                       590                                   0   
3                       393                                   0   
4                       730                                   0   

   Match Won after winning Toss Team B  
0                                    0  
1                                    0  
2                                    0  
3                                    0  
4                                    0  

[5 rows x 25 columns]

In [68]:
df.to_csv("matches_complete.csv")

In [13]:
percentage

2008      2009      2010      2011      2012  \
Kolkata Knight Riders        0.0  0.500000  0.384615  0.450000  0.518519   
Chennai Super Kings          0.0  0.600000  0.583333  0.590909  0.645161   
Rajasthan Royals             0.0  0.818182  0.733333  0.666667  0.642857   
Mumbai Indians               0.0  0.500000  0.500000  0.565217  0.551724   
Deccan Chargers              0.0  0.222222  0.473684  0.500000  0.500000   
Kings XI Punjab              0.0  0.500000  0.571429  0.421053  0.413793   
Royal Challengers Bangalore  0.0  0.200000  0.461538  0.421053  0.520000   
Delhi Daredevils             0.0  0.333333  0.533333  0.565217  0.500000   
Kochi Tuskers Kerala         0.0  0.000000  0.000000  0.000000  0.500000   
Pune Warriors                0.0  0.000000  0.000000  0.000000  0.000000   
Sunrisers Hyderabad          0.0  0.000000  0.000000  0.000000  0.000000   
Rising Pune Supergiants      0.0  0.000000  0.000000  0.000000  0.000000   
Gujarat Lions                0.0  0.000000  0.000000  0.000000  0.000000   
Rising Pune Supergiant       0.0  0.000000  0.000000  0.000000  0.000000   
Delhi Capitals               0.0  0.000000  0.000000  0.000000  0.000000   

                                 2013      2014      2015      2016      2017  \
Kolkata Knight Riders        0.558824  0.500000  0.527273  0.539683  0.550725   
Chennai Super Kings          0.631579  0.673913  0.660714  0.636364  0.636364   
Rajasthan Royals             0.552632  0.551020  0.543860  0.539683  0.539683   
Mumbai Indians               0.550000  0.576923  0.568966  0.553846  0.554054   
Deccan Chargers              0.441860  0.441860  0.441860  0.441860  0.441860   
Kings XI Punjab              0.432432  0.454545  0.490196  0.448276  0.406250   
Royal Challengers Bangalore  0.516129  0.555556  0.511111  0.527273  0.540984   
Delhi Daredevils             0.500000  0.446809  0.411765  0.410714  0.437500   
Kochi Tuskers Kerala         0.500000  0.500000  0.500000  0.500000  0.500000   
Pune Warriors                0.090909  0.150000  0.150000  0.150000  0.150000   
Sunrisers Hyderabad          0.000000  0.142857  0.285714  0.350000  0.466667   
Rising Pune Supergiants      0.000000  0.000000  0.000000  0.000000  0.428571   
Gujarat Lions                0.000000  0.000000  0.000000  0.000000  0.750000   
Rising Pune Supergiant       0.000000  0.000000  0.000000  0.000000  0.000000   
Delhi Capitals               0.000000  0.000000  0.000000  0.000000  0.000000   

                                 2018      2019      2020  
Kolkata Knight Riders        0.564103  0.563218  0.576087  
Chennai Super Kings          0.636364  0.649351  0.640449  
Rajasthan Royals             0.539683  0.536232  0.525000  
Mumbai Indians               0.564706  0.555556  0.571429  
Deccan Chargers              0.441860  0.441860  0.441860  
Kings XI Punjab              0.411765  0.426667  0.432099  
Royal Challengers Bangalore  0.500000  0.506494  0.506173  
Delhi Daredevils             0.458333  0.437500  0.437500  
Kochi Tuskers Kerala         0.500000  0.500000  0.500000  
Pune Warriors                0.150000  0.150000  0.150000  
Sunrisers Hyderabad          0.485714  0.500000  0.500000  
Rising Pune Supergiants      0.428571  0.428571  0.428571  
Gujarat Lions                0.666667  0.666667  0.666667  
Rising Pune Supergiant       0.833333  0.833333  0.833333  
Delhi Capitals               0.000000  0.000000  0.700000

In [14]:
match_count

array([[92.],
       [89.],
       [80.],
       [98.],
       [43.],
       [81.],
       [81.],
       [80.],
       [ 8.],
       [20.],
       [46.],
       [ 7.],
       [15.],
       [ 6.],
       [10.]])

In [15]:
toss_count

array([[53.],
       [57.],
       [42.],
       [56.],
       [19.],
       [35.],
       [41.],
       [35.],
       [ 4.],
       [ 3.],
       [23.],
       [ 3.],
       [10.],
       [ 5.],
       [ 7.]])

In [22]:
x[14][12] = 42/90

In [23]:
x[14][12]

0.4666666666666667

In [26]:
df1 = pd.read_csv('C://Users/Gray/Desktop/git_repos/IPL-2020/Dummy Data/2020_done.csv')

In [27]:
df1

Unnamed: 0  match_day  match_no  day time_IST time_UAE      venue  \
0            0          1         1  SAT   7:30PM   6:00PM  ABU DHABI   
1            1          2         2  SUN   7:30PM   6:00PM      DUBAI   
2            2          3         3  MON   7:30PM   6:00PM      DUBAI   
3            3          4         4  TUE   7:30PM   6:00PM    SHARJAH   
4            4          5         5  WED   7:30PM   6:00PM  ABU DHABI   
5            5          6         6  THU   7:30PM   6:00PM      DUBAI   
6            6          7         7  FRI   7:30PM   6:00PM      DUBAI   
7            7          8         8  SAT   7:30PM   6:00PM  ABU DHABI   
8            8          9         9  SUN   7:30PM   6:00PM    SHARJAH   
9            9         10        10  MON   7:30PM   6:00PM      DUBAI   
10          10         11        11  TUE   7:30PM   6:00PM  ABU DHABI   
11          11         12        12  WED   7:30PM   6:00PM      DUBAI   
12          12         13        13  THU   7:30PM   6:00PM  ABU DHABI   
13          13         14        14  FRI   7:30PM   6:00PM      DUBAI   
14          14         15        15  SAT   3:30PM   2:00PM  ABU DHABI   
15          15         15        16  SAT   7:30PM   6:00PM    SHARJAH   
16          16         16        17  SUN   3:30PM   2:00PM    SHARJAH   
17          17         16        18  SUN   7:30PM   6:00PM      DUBAI   
18          18         17        19  MON   7:30PM   6:00PM      DUBAI   
19          19         18        20  TUE   7:30PM   6:00PM  ABU DHABI   
20          20         19        21  WED   7:30PM   6:00PM  ABU DHABI   
21          21         20        22  THU   7:30PM   6:00PM      DUBAI   
22          22         21        23  FRI   7:30PM   6:00PM    SHARJAH   
23          23         22        24  SAT   3:30PM   2:00PM  ABU DHABI   
24          24         22        25  SAT   7:30PM   6:00PM      DUBAI   
25          25         23        26  SUN   3:30PM   2:00PM      DUBAI   
26          26         23        27  SUN   7:30PM   6:00PM  ABU DHABI   
27          27         24        28  MON   7:30PM   6:00PM    SHARJAH   
28          28         25        29  TUE   7:30PM   6:00PM      DUBAI   
29          29         26        30  WED   7:30PM   6:00PM      DUBAI   
30          30         27        31  THU   7:30PM   6:00PM    SHARJAH   
31          31         28        32  FRI   7:30PM   6:00PM  ABU DHABI   
32          32         29        33  SAT   3:30PM   2:00PM      DUBAI   
33          33         29        34  SAT   7:30PM   6:00PM    SHARJAH   
34          34         30        35  SUN   3:30PM   2:00PM  ABU DHABI   
35          35         30        36  SUN   7:30PM   6:00PM      DUBAI   
36          36         31        37  MON   7:30PM   6:00PM  ABU DHABI   
37          37         32        38  TUE   7:30PM   6:00PM      DUBAI   
38          38         33        39  WED   7:30PM   6:00PM  ABU DHABI   
39          39         34        40  THU   7:30PM   6:00PM      DUBAI   
40          40         35        41  FRI   7:30PM   6:00PM    SHARJAH   
41          41         36        42  SAT   3:30PM   2:00PM  ABU DHABI   
42          42         36        43  SAT   7:30PM   6:00PM      DUBAI   
43          43         37        44  SUN   3:30PM   2:00PM      DUBAI   
44          44         37        45  SUN   7:30PM   6:00PM  ABU DHABI   
45          45         38        46  MON   7:30PM   6:00PM    SHARJAH   
46          46         39        47  TUE   7:30PM   6:00PM      DUBAI   
47          47         40        48  WED   7:30PM   6:00PM  ABU DHABI   
48          48         41        49  THU   7:30PM   6:00PM      DUBAI   
49          49         42        50  FRI   7:30PM   6:00PM  ABU DHABI   
50          50         43        51  SAT   3:30PM   2:00PM      DUBAI   
51          51         43        52  SAT   7:30PM   6:00PM    SHARJAH   
52          52         44        53  SUN   3:30PM   2:00PM  ABU DHABI   
53          53         44        54  SUN   7:30PM   6:00PM    

In [28]:
df1['Match Won after winning Toss Team A'] = 't'
df1['Match Won after winning Toss Team B'] = 't'

In [36]:
for i in range(56):
    season = 2020
    teamA = df1['home'][i]
    teamB = df1['away'][i]
    diff = int(season)-2008
    posA = dict[teamA]
    posB = dict[teamB]
    df1['Match Won after winning Toss Team A'][i] = x[posA][diff]
    df1['Match Won after winning Toss Team B'][i] = x[posB][diff]

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':


In [37]:
df1

Unnamed: 0  match_day  match_no  day time_IST time_UAE      venue  \
0            0          1         1  SAT   7:30PM   6:00PM  ABU DHABI   
1            1          2         2  SUN   7:30PM   6:00PM      DUBAI   
2            2          3         3  MON   7:30PM   6:00PM      DUBAI   
3            3          4         4  TUE   7:30PM   6:00PM    SHARJAH   
4            4          5         5  WED   7:30PM   6:00PM  ABU DHABI   
5            5          6         6  THU   7:30PM   6:00PM      DUBAI   
6            6          7         7  FRI   7:30PM   6:00PM      DUBAI   
7            7          8         8  SAT   7:30PM   6:00PM  ABU DHABI   
8            8          9         9  SUN   7:30PM   6:00PM    SHARJAH   
9            9         10        10  MON   7:30PM   6:00PM      DUBAI   
10          10         11        11  TUE   7:30PM   6:00PM  ABU DHABI   
11          11         12        12  WED   7:30PM   6:00PM      DUBAI   
12          12         13        13  THU   7:30PM   6:00PM  ABU DHABI   
13          13         14        14  FRI   7:30PM   6:00PM      DUBAI   
14          14         15        15  SAT   3:30PM   2:00PM  ABU DHABI   
15          15         15        16  SAT   7:30PM   6:00PM    SHARJAH   
16          16         16        17  SUN   3:30PM   2:00PM    SHARJAH   
17          17         16        18  SUN   7:30PM   6:00PM      DUBAI   
18          18         17        19  MON   7:30PM   6:00PM      DUBAI   
19          19         18        20  TUE   7:30PM   6:00PM  ABU DHABI   
20          20         19        21  WED   7:30PM   6:00PM  ABU DHABI   
21          21         20        22  THU   7:30PM   6:00PM      DUBAI   
22          22         21        23  FRI   7:30PM   6:00PM    SHARJAH   
23          23         22        24  SAT   3:30PM   2:00PM  ABU DHABI   
24          24         22        25  SAT   7:30PM   6:00PM      DUBAI   
25          25         23        26  SUN   3:30PM   2:00PM      DUBAI   
26          26         23        27  SUN   7:30PM   6:00PM  ABU DHABI   
27          27         24        28  MON   7:30PM   6:00PM    SHARJAH   
28          28         25        29  TUE   7:30PM   6:00PM      DUBAI   
29          29         26        30  WED   7:30PM   6:00PM      DUBAI   
30          30         27        31  THU   7:30PM   6:00PM    SHARJAH   
31          31         28        32  FRI   7:30PM   6:00PM  ABU DHABI   
32          32         29        33  SAT   3:30PM   2:00PM      DUBAI   
33          33         29        34  SAT   7:30PM   6:00PM    SHARJAH   
34          34         30        35  SUN   3:30PM   2:00PM  ABU DHABI   
35          35         30        36  SUN   7:30PM   6:00PM      DUBAI   
36          36         31        37  MON   7:30PM   6:00PM  ABU DHABI   
37          37         32        38  TUE   7:30PM   6:00PM      DUBAI   
38          38         33        39  WED   7:30PM   6:00PM  ABU DHABI   
39          39         34        40  THU   7:30PM   6:00PM      DUBAI   
40          40         35        41  FRI   7:30PM   6:00PM    SHARJAH   
41          41         36        42  SAT   3:30PM   2:00PM  ABU DHABI   
42          42         36        43  SAT   7:30PM   6:00PM      DUBAI   
43          43         37        44  SUN   3:30PM   2:00PM      DUBAI   
44          44         37        45  SUN   7:30PM   6:00PM  ABU DHABI   
45          45         38        46  MON   7:30PM   6:00PM    SHARJAH   
46          46         39        47  TUE   7:30PM   6:00PM      DUBAI   
47          47         40        48  WED   7:30PM   6:00PM  ABU DHABI   
48          48         41        49  THU   7:30PM   6:00PM      DUBAI   
49          49         42        50  FRI   7:30PM   6:00PM  ABU DHABI   
50          50         43        51  SAT   3:30PM   2:00PM      DUBAI   
51          51         43        52  SAT   7:30PM   6:00PM    SHARJAH   
52          52         44        53  SUN   3:30PM   2:00PM  ABU DHABI   
53          53         44        54  SUN   7:30PM   6:00PM    

In [38]:
df1.to_csv('2020_done.csv', index=False)